# Generated by Django 4.1.4 on 2023-01-05 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_user_followers_remove_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='likes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relation_follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relation_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
