# Generated by Django 4.1.4 on 2023-01-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comments_content_alter_comments_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
