# Generated by Django 4.1.4 on 2023-01-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_followers_user_following_remove_comments_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
