# Generated by Django 4.1.4 on 2022-12-26 12:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('auction_image', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default=None, max_length=64)),
                ('starting_bid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('current_bid', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8), max_digits=10)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('comment_datetime', models.DateTimeField(default=None)),
                ('auctionID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='AuctionID', to='auctions.auction')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bid_datetime', models.DateTimeField(default=None)),
                ('auctionID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auctionID', to='auctions.auction')),
            ],
        ),
    ]
