# Generated by Django 4.1.4 on 2022-12-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_auctioncomments_auctionbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(default=models.IntegerField(default=1)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='bid',
            field=models.IntegerField(default=1),
        ),
    ]
