# Generated by Django 4.1.4 on 2022-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_current_bid_alter_auction_starting_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(default=1),
        ),
    ]
