# Generated by Django 4.1.4 on 2022-12-28 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='bid_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bid_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctioncomments',
            name='comment_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
