# Generated by Django 4.1.4 on 2022-12-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionbid_bid_owner_auctioncomments_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbid',
            name='auctionID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auctionbid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, unique=True),
        ),
    ]
