# Generated by Django 4.1.4 on 2022-12-30 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionbid_auctionid_alter_auctionbid_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='auction_watchlist', to='auctions.auction')),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
